version: '3'
services:
  flask-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "9696:9696"
    environment:
      - FLASK_ENV=development
      - RUN_ID=7baf08eb142744abb2a41e386fbab279
      - MODEL_URI=${MODEL_URI} 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
      - IMAGE_TAG=promisetacy/salary-prediction:latest

  nginx-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
