name: Deploy MLflow and Prefect

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy MLflow, Prefect, .env and Docker Compose Files to EC2
        run: |
          scp -i infrastructure/mlops1.pem -r /mlflow/ /orchestration/ /.env /docker-compose.yml ec2-user@your-ec2-instance:~

      - name: SSH into EC2 and Build and run Docker Compose
        run: |
          # SSH into your EC2 instance and build Docker images there.
          ssh -i infrastructure/mlops1.pem ec2-user@your-ec2-instance sudo docker-compose up --build -d

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Destroy Terraform Infrastructure
        run: terraform destroy -auto-approve
