active = "default"

[profiles.default]
PREFECT_UI_API_URL = "http://prefect_server:4200/api"

[server]
host = "http:/prefect_server"
port = "4200"
host_port = "4200"
endpoint = "${server.host}:${server.port}"
